name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v7.0.1

      - name: Install Deno
        uses: denoland/setup-deno@v2.0.5
        with:
          deno-version: 2.9.4

      - name: Run tests
        run: deno task test:all
